###############################################################################
# Snakemake pipeline for construction of the cancer targetome file 
# Author: Nathaniel Evans  |  created: 2025‑05‑05
###############################################################################

import os, datetime
import yaml

# ---------------------------------------------------------------------------
# Directory structure
# ---------------------------------------------------------------------------

configfile: "config.yaml"
cfg = config

RUN_ID  = cfg["run_id"]
PROC_ID = cfg["proc_id"]

RAW_DIR  = cfg["dirs"]["data"]
RUNS_DIR = cfg["dirs"]["runs"]

PROC_DIR = os.path.join(RUNS_DIR, "proc", PROC_ID)
RUN_ROOT = os.path.join(RUNS_DIR, "exp",  RUN_ID)
OUT_DIR  = os.path.join(RUN_ROOT, "output")

VAE_DIR  = os.path.join(OUT_DIR, "vae")
DT_DIR   = os.path.join(OUT_DIR, "deeptraj")

VAE_MODEL = os.path.join(VAE_DIR, "models", cfg["models"]["vae"])
DT_MODEL  = os.path.join(DT_DIR,  "models", cfg["models"]["deeptraj"])

# ---------------------------------------------------------------------------
# Rule graph
# ---------------------------------------------------------------------------
rule all:
    input:
        DT_MODEL,
        os.path.join(OUT_DIR, "dti", "mean_results.txt"),
        os.path.join(OUT_DIR, "viz", "proj_embeddings.png"),
        os.path.join(OUT_DIR, "eval", "repl_hold_out_results_mean.csv"),
        os.path.join(OUT_DIR, "batch_cmp", "batch_prediction_comparison.csv"),
        os.path.join(OUT_DIR, "diff_expr", "differential_expression_lincs_level5_comparison.csv"),
        os.path.join(OUT_DIR, "predict_grid", "pred_meta.csv")

# ---------------------------------------------------------------------------
rule get_data:
    """
    Download Phase‑II LINCS L1000 datasets & metadata.
    Creates a sentinel '.done' file so the rule is easily cached.
    """
    output:
        flag = os.path.join(RAW_DIR, ".download_complete")
    params:
        script = cfg["scripts"]["get_data"]
    shell:
        """
        bash {params.script} {DATA_DIR}
        touch {output.flag}
        """